// src/constants/tours.js

export const TOURS = [
  // 1. RẠCH GIÁ CITY TOUR
  {
    id: "tour-rach-gia-city-1d",
    name: "Rạch Giá – Biển & Di sản",
    duration: "1 ngày",
    durationType: "1N",
    theme: "City tour – biển – văn hóa",
    category: "bien_dao",
    color: "#f97316",
    startCity: "Rạch Giá",
    stops: [
      "Bến tàu cao tốc Rạch Giá",
      "Công viên Bãi Dương",
      "Chùa Sắc Tứ Tam Bảo",
      "Quảng trường Trần Quang Khải",
      "Bảo tàng Kiên Giang.",
      "Chùa Phổ Minh",
    ],
    stopsCount: 6,
    distanceKm: 12,
    moveTimeMin: 35,
    timeline: [
      { time: "08:00", label: "Bến tàu cao tốc Rạch Giá – check-in, chụp ảnh" },
      { time: "09:00", label: "Công viên Bãi Dương – dạo biển, cà phê" },
      { time: "10:30", label: "Chùa Sắc Tứ Tam Bảo – tham quan, chiêm bái" },
      { time: "14:00", label: "Quảng trường Trần Quang Khải – vui chơi, chụp ảnh" },
      { time: "15:30", label: "Bảo tàng Kiên Giang – tìm hiểu lịch sử địa phương" },
      { time: "17:00", label: "Chùa Phổ Minh – kết thúc hành trình trong ngày" },
    ],
  },

  // 2. LONG XUYÊN – KÝ ỨC SÔNG HẬU
  {
    id: "tour-long-xuyen-heritage-1d",
    name: "Long Xuyên – Sông Hậu & Ký ức Tôn Đức Thắng",
    duration: "1 ngày",
    durationType: "1N",
    theme: "Văn hóa – lịch sử – sinh thái ven sông",
    category: "van_hoa",
    color: "#22c55e",
    startCity: "Long Xuyên",
    stops: [
      "Bảo tàng An Giang",
      "Nhà thờ Chánh tòa Long Xuyên",
      "Khu Du Lịch Sinh Thái Ven Đô",
      "Khu lưu niệm Chủ tịch Tôn Đức Thắng",
    ],
    stopsCount: 4,
    distanceKm: 10,
    moveTimeMin: 30,
    timeline: [
      { time: "08:00", label: "Bảo tàng An Giang – tham quan trưng bày" },
      { time: "09:30", label: "Nhà thờ Chánh tòa Long Xuyên – ngắm kiến trúc" },
      { time: "14:00", label: "Khu DLST Ven Đô – nghỉ ngơi, chụp ảnh ven sông" },
      { time: "16:00", label: "Khu lưu niệm Chủ tịch Tôn Đức Thắng – tìm hiểu lịch sử" },
    ],
  },

  // 3. KHÔNG GIAN ÓC EO – NÚI BA THÊ
  {
    id: "tour-oc-eo-ba-the-1d",
    name: "Không gian Óc Eo – Núi Ba Thê",
    duration: "1 ngày",
    durationType: "1N",
    theme: "Khảo cổ – văn hóa – núi non",
    category: "sinh_thai",
    color: "#0ea5e9",
    startCity: "Thoại Sơn",
    stops: [
      "Núi Ba Thê (Núi Linh Sơn)",
      "Bảo tàng Văn hóa Óc Eo",
      "Di tích Văn hóa Óc Eo (Di tích Linh Sơn Nam)",
      "Đền thờ Thoại Ngọc Hầu",
    ],
    stopsCount: 4,
    distanceKm: 18,
    moveTimeMin: 45,
    timeline: [
      { time: "07:30", label: "Khởi hành lên Núi Ba Thê (Núi Linh Sơn)" },
      { time: "09:00", label: "Chinh phục các điểm cao, ngắm toàn cảnh Thoại Sơn" },
      { time: "11:00", label: "Bảo tàng Văn hóa Óc Eo – tham quan hiện vật khảo cổ" },
      { time: "14:00", label: "Di tích Linh Sơn Nam – tìm hiểu không gian Óc Eo" },
      { time: "16:00", label: "Đền thờ Thoại Ngọc Hầu – kết thúc ngày tham quan" },
    ],
  },

  // 4. THOẠI SƠN – NÚI SẬP & HỒ NÚI
  {
    id: "tour-thoai-son-2d1n",
    name: "Thoại Sơn – Núi Sập & Hồ Núi",
    duration: "2 ngày 1 đêm",
    durationType: "2N1D",
    theme: "Tự nhiên – tâm linh – nghỉ dưỡng",
    category: "sinh_thai",
    color: "#6366f1",
    startCity: "Thoại Sơn",
    stops: [
      "Công viên Núi Sập",
      "Thiền Viện Trúc Lâm An Giang",
      "Hồ Thủy Linh Sơn",
      "Đồi Mộng Mơ",
    ],
    stopsCount: 4,
    distanceKm: 22,
    moveTimeMin: 55,
    timeline: [
      { time: "Ngày 1 - 08:00", label: "Công viên Núi Sập – check-in cảnh quan núi" },
      { time: "Ngày 1 - 10:30", label: "Thiền Viện Trúc Lâm An Giang – hành hương, tĩnh tâm" },
      { time: "Ngày 1 - 15:00", label: "Hồ Thủy Linh Sơn – trải nghiệm không gian hồ núi" },
      { time: "Ngày 2 - 08:30", label: "Đồi Mộng Mơ – săn mây, ngắm bình minh" },
    ],
  },

  // 5. CÙ LAO GIÊNG – LÀNG NGHỀ & SINH THÁI
  {
    id: "tour-cu-lao-gieng-1d",
    name: "Cù Lao Giêng – Làng nghề & sinh thái",
    duration: "1 ngày",
    durationType: "1N",
    theme: "Du lịch cộng đồng – tâm linh – sông nước",
    category: "lang_nghe",
    color: "#84cc16",
    startCity: "Cù Lao Giêng",
    stops: [
      "Khu Du Lịch Sinh Thái Cồn Én",
      "Chùa Đạo Nằm (Phước Minh Tự)",
      "Chùa Phước Thành",
      "Làng nuôi cá Bè Châu Đốc",
    ],
    stopsCount: 4,
    distanceKm: 20,
    moveTimeMin: 50,
    timeline: [
      { time: "08:00", label: "KDLST Cồn Én – trải nghiệm sông nước, xuồng máy" },
      { time: "10:00", label: "Chùa Đạo Nằm (Phước Minh Tự) – chiêm bái" },
      { time: "14:00", label: "Chùa Phước Thành – tham quan kiến trúc tôn giáo" },
      { time: "16:00", label: "Làng bè Châu Đốc – tham quan mô hình nuôi cá trên sông" },
    ],
  },

  // 6. CHÂU ĐỐC – NÚI SAM TÂM LINH KINH ĐIỂN
  {
    id: "tour-chau-doc-nui-sam-1d",
    name: "Châu Đốc – Núi Sam tâm linh",
    duration: "1 ngày",
    durationType: "1N",
    theme: "Du lịch tâm linh – văn hóa",
    category: "tam_linh",
    color: "#ec4899",
    startCity: "Châu Đốc",
    stops: [
      "Miếu Bà Chúa Xứ",
      "Chùa Tây An Cổ Tự",
      "Lăng Thoại Ngọc Hầu",
      "Chùa Hang - Phước Điền Tự",
      "Chùa Huỳnh Đạo",
      "Núi Sam",
    ],
    stopsCount: 6,
    distanceKm: 16,
    moveTimeMin: 40,
    timeline: [
      { time: "07:30", label: "Miếu Bà Chúa Xứ – viếng Bà, cầu bình an" },
      { time: "09:00", label: "Chùa Tây An Cổ Tự – tham quan kiến trúc cổ" },
      { time: "10:30", label: "Lăng Thoại Ngọc Hầu – tìm hiểu công lao khai khẩn" },
      { time: "14:00", label: "Chùa Hang - Phước Điền Tự – ngắm toàn cảnh Núi Sam" },
      { time: "15:30", label: "Chùa Huỳnh Đạo – check-in hồ sen, không gian tĩnh lặng" },
      { time: "17:00", label: "Tổng quan Núi Sam – kết thúc hành trình tâm linh" },
    ],
  },

  // 7. BẢY NÚI – TREKKING & TÂM LINH
  {
    id: "tour-bay-nui-2d1n",
    name: "Bảy Núi – Trekking & tâm linh",
    duration: "2 ngày 1 đêm",
    durationType: "2N1D",
    theme: "Leo núi – sinh thái – tâm linh",
    category: "sinh_thai",
    color: "#14b8a6",
    startCity: "Tịnh Biên",
    stops: [
      "Núi Cấm",
      "Hồ Thủy Linh Sơn",
      "Chùa Vạn Linh",
      "Núi Két",
      "Núi Dài",
      "Núi Cô Tô",
      "Núi Tượng",
      "Núi Nước",
      "Núi Trà Sư",
    ],
    stopsCount: 9,
    distanceKm: 40,
    moveTimeMin: 90,
    timeline: [
      { time: "Ngày 1 - 07:30", label: "Núi Cấm – cáp treo / leo núi, ngắm toàn cảnh" },
      { time: "Ngày 1 - 10:00", label: "Hồ Thủy Linh Sơn – nghỉ chân, chụp ảnh" },
      { time: "Ngày 1 - 14:00", label: "Chùa Vạn Linh – tham quan, cầu an" },
      { time: "Ngày 2 - 07:30", label: "Chuỗi Núi Két – Núi Dài – Núi Cô Tô – trekking nhẹ" },
      { time: "Ngày 2 - 14:00", label: "Núi Tượng – Núi Nước – Núi Trà Sư (tùy thời gian đoàn)" },
    ],
  },

  // 8. TRÀ SƯ – CÁNH ĐỒNG THỐT NỐT
  {
    id: "tour-tra-su-thot-not-1d",
    name: "Rừng tràm Trà Sư & Cánh đồng Thốt Nốt",
    duration: "1 ngày",
    durationType: "1N",
    theme: "Sinh thái ngập nước – cảnh quan đặc trưng",
    category: "sinh_thai",
    color: "#a855f7",
    startCity: "Tịnh Biên",
    stops: [
      "Rừng Tràm Trà Sư",
      "Cánh đồng Thốt Nốt - Vĩnh Trung - An Giang",
      "Chùa Lầu - Phước Lâm Tự",
      "Chùa Kim Tiên",
      "Miếu bà Chúa Xứ Bàu Mướp",
    ],
    stopsCount: 5,
    distanceKm: 28,
    moveTimeMin: 70,
    timeline: [
      { time: "07:30", label: "Rừng Tràm Trà Sư – đi xuồng len lỏi rừng tràm" },
      { time: "10:30", label: "Cánh đồng Thốt Nốt Vĩnh Trung – check-in 'cây thốt nốt đôi'" },
      { time: "14:00", label: "Chùa Lầu - Phước Lâm Tự – ngắm kiến trúc 'chùa lơ lửng'" },
      { time: "15:30", label: "Chùa Kim Tiên – toàn cảnh vùng Bảy Núi" },
      { time: "16:30", label: "Miếu bà Chúa Xứ Bàu Mướp – viếng Bà" },
    ],
  },

  // 9. TRI TÔN – HỒ NÚI & TỨC DỤP
  {
    id: "tour-tri-ton-1d",
    name: "Tri Tôn – Hồ núi & Đồi Tức Dụp",
    duration: "1 ngày",
    durationType: "1N",
    theme: "Sinh thái – lịch sử chiến tranh",
    category: "sinh_thai",
    color: "#eab308",
    startCity: "Tri Tôn",
    stops: [
      "Hồ Soài So",
      "Hồ Ô Thum",
      "Hồ Đá Đồi Tà Pạ",
      "Khu du lịch Đồi Tức Dụp",
    ],
    stopsCount: 4,
    distanceKm: 25,
    moveTimeMin: 60,
    timeline: [
      { time: "08:00", label: "Hồ Soài So – không gian hồ núi trong lành" },
      { time: "10:00", label: "Hồ Ô Thum – thưởng thức gà nướng 'trứ danh'" },
      { time: "14:00", label: "Hồ Đá Đồi Tà Pạ – check-in hồ trên đồi đá" },
      { time: "15:30", label: "Đồi Tức Dụp – tìm hiểu chiến khu xưa" },
    ],
  },

  // 10. LÀNG NGHỀ AN GIANG
  {
    id: "tour-lang-nghe-an-giang-1d",
    name: "An Giang – Làng nghề & sông nước",
    duration: "1 ngày",
    durationType: "1N",
    theme: "Du lịch cộng đồng – làng nghề",
    category: "lang_nghe",
    color: "#ef4444",
    startCity: "Châu Đốc",
    stops: [
      "Làng dệt thổ cẩm Châu Phong",
      "Làng lụa Tân Châu",
      "Làng nuôi cá Bè Châu Đốc",
    ],
    stopsCount: 3,
    distanceKm: 30,
    moveTimeMin: 75,
    timeline: [
      { time: "08:00", label: "Làng dệt thổ cẩm Châu Phong – trải nghiệm nghề dệt" },
      { time: "10:30", label: "Làng lụa Tân Châu – xem quy trình nhuộm 'lãnh Mỹ A'" },
      { time: "15:00", label: "Làng nuôi cá Bè Châu Đốc – khám phá cuộc sống sông nước" },
    ],
  },

  // 11. HÀ TIÊN – BIỂN NÚI & CHÙA CỔ
  {
    id: "tour-ha-tien-2d1n",
    name: "Hà Tiên – Biển, núi & chùa cổ",
    duration: "2 ngày 1 đêm",
    durationType: "2N1D",
    theme: "Biển – núi – tâm linh",
    category: "bien_dao",
    color: "#22c55e",
    startCity: "Hà Tiên",
    stops: ["Bãi Sau Mũi Nai", "Núi Bình San", "Phù Dung cổ tự"],
    stopsCount: 3,
    distanceKm: 35,
    moveTimeMin: 80,
    timeline: [
      { time: "Ngày 1 - 08:00", label: "Bãi Sau Mũi Nai – tắm biển, vui chơi" },
      { time: "Ngày 1 - 16:00", label: "Núi Bình San – ngắm hoàng hôn Hà Tiên" },
      { time: "Ngày 2 - 08:30", label: "Phù Dung cổ tự – tham quan chùa cổ, kết thúc tour" },
    ],
  },

  // 12. KIÊN LƯƠNG – HÒN PHỤ TỬ & BA HÒN ĐẦM
  {
    id: "tour-kien-luong-1d",
    name: "Kiên Lương – Hòn Phụ Tử & ba hòn Đầm",
    duration: "1 ngày",
    durationType: "1N",
    theme: "Biển đảo – cảnh quan kỳ thú",
    category: "bien_dao",
    color: "#3b82f6",
    startCity: "Kiên Lương",
    stops: [
      "Hòn Đầm Đước",
      "Hòn Đầm Giếng",
      "Hòn Phụ Tử",
      "Khu du lịch Chùa Hang - Hòn Phụ Tử",
    ],
    stopsCount: 4,
    distanceKm: 26,
    moveTimeMin: 65,
    timeline: [
      { time: "08:00", label: "Xuất phát tham quan cụm Hòn Đầm Đước – Đầm Giếng" },
      { time: "11:00", label: "Hòn Phụ Tử – chiêm ngưỡng biểu tượng Kiên Lương" },
      { time: "14:00", label: "KDL Chùa Hang - Hòn Phụ Tử – tắm biển, tham quan chùa Hang" },
    ],
  },

  // 13. NAM DU – ĐẢO XANH HOANG SƠ
  {
    id: "tour-nam-du-2d1n",
    name: "Quần đảo Nam Du – Biển xanh hoang sơ",
    duration: "2 ngày 1 đêm",
    durationType: "2N1D",
    theme: "Biển đảo – nghỉ dưỡng – khám phá",
    category: "bien_dao",
    color: "#f97316",
    startCity: "Rạch Giá",
    stops: ["Quần đảo Nam Du", "Bãi Cây Mến"],
    stopsCount: 2,
    distanceKm: 40,
    moveTimeMin: 90,
    timeline: [
      { time: "Ngày 1 - 07:00", label: "Tàu cao tốc từ Rạch Giá ra Nam Du" },
      { time: "Ngày 1 - 10:00", label: "Quần đảo Nam Du – nhận phòng, nghỉ ngơi" },
      { time: "Ngày 2 - 08:00", label: "Bãi Cây Mến – tắm biển, chụp ảnh 'view xanh'" },
      { time: "Ngày 2 - 13:00", label: "Lên tàu về lại Rạch Giá" },
    ],
  },

  // 14. RẠCH GIÁ – CỬA NGÕ RA ĐẢO
  {
    id: "tour-rach-gia-nam-du-2d1n",
    name: "Rạch Giá – Cửa ngõ ra đảo Nam Du",
    duration: "2 ngày 1 đêm",
    durationType: "2N1D",
    theme: "City tour – biển – nối tuyến đảo",
    category: "bien_dao",
    color: "#10b981",
    startCity: "Rạch Giá",
    stops: [
      "Bến tàu cao tốc Rạch Giá",
      "Công viên Bãi Dương",
      "Quảng trường Trần Quang Khải",
      "Quần đảo Nam Du",
      "Bãi Cây Mến",
    ],
    stopsCount: 5,
    distanceKm: 45,
    moveTimeMin: 100,
    timeline: [
      { time: "Ngày 1 - 08:00", label: "City tour Rạch Giá (Bãi Dương, Quảng trường)" },
      { time: "Ngày 1 - 13:00", label: "Bến tàu cao tốc – di chuyển ra Nam Du" },
      { time: "Ngày 2 - 08:00", label: "Bãi Cây Mến – vui chơi, tắm biển" },
      { time: "Ngày 2 - 13:00", label: "Tàu về lại Rạch Giá – kết thúc hành trình" },
    ],
  },

  // 15. PHÚ QUỐC 3N2Đ – RỪNG, BIỂN & GIẢI TRÍ
  {
    id: "tour-phu-quoc-3n2d",
    name: "Phú Quốc 3N2Đ – Rừng, biển & giải trí",
    duration: "3 ngày 2 đêm",
    durationType: "3N2D",
    theme: "Nghỉ dưỡng – sinh thái – vui chơi",
    category: "bien_dao",
    color: "#0f766e",
    startCity: "Phú Quốc",
    stops: [
      "Khu du lịch sinh thái (Suối Đá Bàn)",
      "Vườn Quốc Gia Phú Quốc",
      "Làng chài Rạch Tràm",
      "Grand World Phú Quốc",
      "Vinpearl Safari",
      "Hòn Thơm Paradise Island.",
      "Di tích Lịch sử Nhà tù Phú Quốc",
      "Chùa Hộ Quốc",
      "Thánh Thất Dương Đông",
    ],
    stopsCount: 9,
    distanceKm: 65,
    moveTimeMin: 130,
    timeline: [
      { time: "Ngày 1 - 08:00", label: "Suối Đá Bàn – trekking nhẹ, tắm suối (mùa nước)" },
      { time: "Ngày 1 - 14:00", label: "Vườn Quốc Gia Phú Quốc – khám phá rừng nguyên sinh" },
      { time: "Ngày 2 - 08:00", label: "Làng chài Rạch Tràm – trải nghiệm đời sống ngư dân" },
      { time: "Ngày 2 - 14:00", label: "Vinpearl Safari – tham quan vườn thú bán hoang dã" },
      { time: "Ngày 2 - 19:00", label: "Grand World – phố đêm, show diễn" },
      { time: "Ngày 3 - 08:00", label: "Hòn Thơm Paradise Island – cáp treo, vui chơi biển" },
      { time: "Ngày 3 - 14:00", label: "Nhà tù Phú Quốc – di tích lịch sử", },
      { time: "Ngày 3 - 16:00", label: "Chùa Hộ Quốc – Thánh Thất Dương Đông (tùy thời gian)" },
    ],
  },

  // 16. PHÚ QUỐC – BẮC ĐẢO XANH
  {
    id: "tour-phu-quoc-bac-dao-1d",
    name: "Phú Quốc – Bắc đảo xanh",
    duration: "1 ngày",
    durationType: "1N",
    theme: "Sinh thái – rừng nguyên sinh",
    category: "bien_dao",
    color: "#fb7185",
    startCity: "Phú Quốc",
    stops: [
      "Vườn Quốc Gia Phú Quốc",
      "Khu du lịch sinh thái (Suối Đá Bàn)",
      "Làng chài Rạch Tràm",
    ],
    stopsCount: 3,
    distanceKm: 22,
    moveTimeMin: 55,
    timeline: [
      { time: "08:00", label: "Vườn Quốc Gia Phú Quốc – trekking, khám phá rừng" },
      { time: "11:00", label: "Suối Đá Bàn – nghỉ trưa, tắm suối (mùa nước)" },
      { time: "15:00", label: "Làng chài Rạch Tràm – ăn hải sản, tham quan" },
    ],
  },

  // 17. PHÚ QUỐC – NAM ĐẢO LỊCH SỬ & TÂM LINH
  {
    id: "tour-phu-quoc-nam-dao-1d",
    name: "Phú Quốc – Nam đảo lịch sử & tâm linh",
    duration: "1 ngày",
    durationType: "1N",
    theme: "Lịch sử – tâm linh – ngắm biển",
    category: "bien_dao",
    color: "#4f46e5",
    startCity: "Phú Quốc",
    stops: [
      "Di tích Lịch sử Nhà tù Phú Quốc",
      "Chùa Hộ Quốc",
      "Thánh Thất Dương Đông",
    ],
    stopsCount: 3,
    distanceKm: 20,
    moveTimeMin: 50,
    timeline: [
      { time: "08:00", label: "Nhà tù Phú Quốc – tham quan di tích lịch sử" },
      { time: "10:30", label: "Chùa Hộ Quốc – ngắm biển từ trên cao" },
      { time: "15:00", label: "Thánh Thất Dương Đông – tham quan kiến trúc tôn giáo" },
    ],
  },

  // 18. COMBO AN GIANG 3N2Đ – TÂM LINH & SINH THÁI
  {
    id: "tour-an-giang-combo-3n2d",
    name: "An Giang 3N2Đ – Tâm linh & Bảy Núi",
    duration: "3 ngày 2 đêm",
    durationType: "3N2D",
    theme: "Tâm linh – sinh thái – làng nghề",
    category: "tam_linh",
    color: "#65a30d",
    startCity: "Châu Đốc",
    stops: [
      // Ngày 1: Châu Đốc – Núi Sam
      "Miếu Bà Chúa Xứ",
      "Chùa Tây An Cổ Tự",
      "Lăng Thoại Ngọc Hầu",
      "Chùa Hang - Phước Điền Tự",
      // Ngày 2: Bảy Núi
      "Núi Cấm",
      "Chùa Vạn Linh",
      "Rừng Tràm Trà Sư",
      "Cánh đồng Thốt Nốt - Vĩnh Trung - An Giang",
      // Ngày 3: Làng nghề & Long Xuyên
      "Làng dệt thổ cẩm Châu Phong",
      "Làng lụa Tân Châu",
      "Khu Du Lịch Sinh Thái Ven Đô",
    ],
    stopsCount: 11,
    distanceKm: 80,
    moveTimeMin: 150,
    timeline: [
      { time: "Ngày 1 - 07:30", label: "Miếu Bà, Chùa Tây An, Lăng Thoại Ngọc Hầu, Chùa Hang" },
      { time: "Ngày 2 - 08:00", label: "Núi Cấm – Chùa Vạn Linh – tham quan Bảy Núi" },
      { time: "Ngày 2 - 14:00", label: "Rừng Tràm Trà Sư – Cánh đồng Thốt Nốt" },
      { time: "Ngày 3 - 08:00", label: "Làng dệt thổ cẩm Châu Phong – Làng lụa Tân Châu" },
      { time: "Ngày 3 - 14:00", label: "KDLST Ven Đô – kết thúc hành trình tại Long Xuyên" },
    ],
  },
];
